# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_server import data_pb2 as grpc__server_dot_data__pb2


class GetWord2VecStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoGetWord2Vec = channel.unary_unary(
        '/ner.GetWord2Vec/DoGetWord2Vec',
        request_serializer=grpc__server_dot_data__pb2.WordSeq.SerializeToString,
        response_deserializer=grpc__server_dot_data__pb2.Word2VecSeq.FromString,
        )


class GetWord2VecServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoGetWord2Vec(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetWord2VecServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoGetWord2Vec': grpc.unary_unary_rpc_method_handler(
          servicer.DoGetWord2Vec,
          request_deserializer=grpc__server_dot_data__pb2.WordSeq.FromString,
          response_serializer=grpc__server_dot_data__pb2.Word2VecSeq.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ner.GetWord2Vec', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
