# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/data.proto',
  package='ner',
  syntax='proto3',
  serialized_pb=_b('\n\x10proto/data.proto\x12\x03ner\"\x1b\n\x07WordSeq\x12\x10\n\x08word_seq\x18\x01 \x03(\t\"\x17\n\x08Word2Vec\x12\x0b\n\x03vec\x18\x01 \x03(\x02\"-\n\x0bWord2VecSeq\x12\x1e\n\x07vec_seq\x18\x01 \x03(\x0b\x32\r.ner.Word2Vec2@\n\x0bGetWord2Vec\x12\x31\n\rDoGetWord2Vec\x12\x0c.ner.WordSeq\x1a\x10.ner.Word2VecSeq\"\x00\x62\x06proto3')
)




_WORDSEQ = _descriptor.Descriptor(
  name='WordSeq',
  full_name='ner.WordSeq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word_seq', full_name='ner.WordSeq.word_seq', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=52,
)


_WORD2VEC = _descriptor.Descriptor(
  name='Word2Vec',
  full_name='ner.Word2Vec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='ner.Word2Vec.vec', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=77,
)


_WORD2VECSEQ = _descriptor.Descriptor(
  name='Word2VecSeq',
  full_name='ner.Word2VecSeq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec_seq', full_name='ner.Word2VecSeq.vec_seq', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=124,
)

_WORD2VECSEQ.fields_by_name['vec_seq'].message_type = _WORD2VEC
DESCRIPTOR.message_types_by_name['WordSeq'] = _WORDSEQ
DESCRIPTOR.message_types_by_name['Word2Vec'] = _WORD2VEC
DESCRIPTOR.message_types_by_name['Word2VecSeq'] = _WORD2VECSEQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordSeq = _reflection.GeneratedProtocolMessageType('WordSeq', (_message.Message,), dict(
  DESCRIPTOR = _WORDSEQ,
  __module__ = 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:ner.WordSeq)
  ))
_sym_db.RegisterMessage(WordSeq)

Word2Vec = _reflection.GeneratedProtocolMessageType('Word2Vec', (_message.Message,), dict(
  DESCRIPTOR = _WORD2VEC,
  __module__ = 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:ner.Word2Vec)
  ))
_sym_db.RegisterMessage(Word2Vec)

Word2VecSeq = _reflection.GeneratedProtocolMessageType('Word2VecSeq', (_message.Message,), dict(
  DESCRIPTOR = _WORD2VECSEQ,
  __module__ = 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:ner.Word2VecSeq)
  ))
_sym_db.RegisterMessage(Word2VecSeq)



_GETWORD2VEC = _descriptor.ServiceDescriptor(
  name='GetWord2Vec',
  full_name='ner.GetWord2Vec',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=126,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoGetWord2Vec',
    full_name='ner.GetWord2Vec.DoGetWord2Vec',
    index=0,
    containing_service=None,
    input_type=_WORDSEQ,
    output_type=_WORD2VECSEQ,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETWORD2VEC)

DESCRIPTOR.services_by_name['GetWord2Vec'] = _GETWORD2VEC

# @@protoc_insertion_point(module_scope)
